services:
  - type: web
    name: crypto-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4 